### ISSUE TITLE
Attempted to load class "SugarRESTServer" from namespace 

### ISSUE THREAD

**Issue by alainhl** [NeoArno/sugar-rest-bundle#2]
Hi guys, 

I'm getting the following error when trying to get the sugar server service: 

Attempted to load class "SugarRESTServer" from namespace "NeoArno\sugarRESTBundle\SugarREST" in /home/alain/code/proyect1/app/cache/dev/appDevDebugProjectContainer.php line 2754. Do you need to "use" it from another namespace?

In my controller I got the following: 

        $sugaruser = $this->container->get('sugarserver');

Does anybody knows why is this happenig??

**Comment by NeoArno** [comment]
Hi,
There is a name problem with directory :
>`SugarRestBundle -> sugarRestBundle`
>`sugarREST -> SugarREST`

And for some class :

>`sugarRESTBean.php -> SugarRESTBean.php`
>`...`

;-)

**Comment by alainhl** [comment]
Hi, 
Thanks you very much! I have updated the names and it's working now. 

Is there a way we can fix this on master??

**Comment by NeoArno** [comment]
Yes Alain, 

you can send me the corrected package
because I have no time to update it for instance :-(

Thanks

Arno

**Comment by alainhl** [comment]
I have forked the repo, fixed and tested the name issues. https://github.com/alainhl/sugar-rest-bundle 

I have also noticed tha your blog is down http://blog.neoarno.com/wp-content/uploads/2013/08/SugarCRMRESTBundle-DevDoc-0.2.pdf 

Thank you very much.

**Comment by NeoArno** [comment]
Thanks Alain ;-)
